# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.202.1/containers/rust/.devcontainer/base.Dockerfile

ARG VARIANT="buster"
FROM mcr.microsoft.com/devcontainers/rust:${VARIANT}
